const en = {
  home: "Home",
  aboutMe: "About me",
  portfolio: "Portfolio",
  blog: "Blog",
  contact: "Contact",
  introHeading: "Welcome to My Page",
  introText: "Assalamu alaykum! Welcome to my page! On this page you can find my portfolio, news in the field of programming, podcasts and a brief description of myself",
  introYouTubeHeading: "The best teacher in learning",
  introYouTubeText: "Is it just me or Uzbeks are one of the best, if not the best, in explaining everything? Like if you have a video with a nice interaction and examples (funny as well), you can learn everything much easier. You don't need any compex examples and monotone lecture. Teaching should be fun and interactive and cooperative. You can understand everything what they say, you can see nice examples and they let you to try it then, with enthusiasm. This is something that should be everywhere, especially where there is a lack of it. Thank you so much for these videos, and similar ones. They are true help and you get much better knowledge of everything. Also thanks to YouTube to connect us with the stuff and connect people around the world!! :)",
  copyright: "© Copyright 2021 All rights reserved",
  name: "Name",
  age: "Age",
  eMail: "E-mail",
  address: "Address",
  subject: "Subject",
  omon: "Omon",
  address44: "44 Choshtepa Tashkent",
  developer: "Junior Developer",
  date: "till September 10, 2020",
  viewSite: "View site",
  contactMe: "Contact",
  me: "Me",
  contactMeText: "Please fill out the form below to contact me",
  contactName: "Enter your name",
  contactEmail: "Enter your email",
  contactMessage: "Enter your message",
  contactSubmit: "Submit",
}

const ru = {
  home: "Домой",
  aboutMe: "Обо мне",
  portfolio: "Портфолио",
  blog: "Блог",
  contact: "Контакт",
  introHeading: "Добро пожаловать на мою страницу",
  introText: "Assalamu alaykum! Добро пожаловать на мою страницу! На этой странице вы можете найти мое портфолио, новости в сфере программирования, подкасты и краткое описание себя.",
  introYouTubeHeading: "Лучший учитель в обучении",
  introYouTubeText: "Только я или узбеки одни из лучших, если не лучшие, все объясняют? Например, если у вас есть видео с приятным взаимодействием и примерами (в том числе и забавными), вы можете научиться всему намного проще. Не нужны сложные примеры и монотонная лекция. Обучение должно быть веселым, интерактивным и коллективным. Вы можете понять все, что они говорят, вы можете увидеть хорошие примеры, и они позволят вам попробовать это с энтузиазмом. Это то, что должно быть везде, особенно там, где этого не хватает. Большое спасибо за эти и похожие видео. Они настоящие помощники, и вы лучше обо всем узнаете. Также спасибо YouTube за то, что он связывает нас с вещами и связывает людей со всего мира !! :)",
  copyright: "© Copyright 2021 Все права защищены",
  name: "Имя",
  age: "Возраст",
  eMail: "Э-мейл",
  address: "Адрес",
  subject: "Профессия",
  omon: "Омон",
  address44: "Ташкент, сергели 44",
  developer: "Юниор разработчик",
  date: "до 10 сентября 2020 г.",
  viewSite: "Посмотреть сайт",
  contactMe: "Cвяжитесь",
  me: "Cо мной",
  contactMeText: "Пожалуйста, заполните форму ниже, чтобы связаться со мной",
  contactName: "Введите ваше имя",
  contactEmail: "Введите адрес электронной почты",
  contactMessage: "Введите сообщение",
  contactSubmit: "Подавать",
}

const uz = {
  home: "Uy",
  aboutMe: "Men haqimda",
  portfolio: "Portfolio",
  blog: "Blog",
  contact: "Kontakt",
  introHeading: "Mening sahifamga xush kelibsiz",
  introText: "Assalamu alaykum!Mening sahifamga xush kelibsiz! Ushbu sahifada mening portfelimni, dasturlash sohasidagi yangiliklarni, podkastlarni va o'zimning qisqacha tavsifimni topishingiz mumkin",
  introYouTubeHeading: "O'qishdagi eng yaxshi o'qituvchi",
  introYouTubeText: "Faqat menmi yoki o'zbeklar hammasini tushuntirishda eng yaxshilaridan biri, hatto eng yaxshisi? Agar sizda yoqimli o'zaro aloqalar va misollar bilan video (masalan, kulgili) bo'lsa, siz hamma narsani osonroq bilib olishingiz mumkin. Sizga biron bir kompeks misollari va monoton ma'ruzalar kerak emas. O'qitish qiziqarli va interaktiv va hamkorlikda bo'lishi kerak. Siz ularning aytganlarini hamma narsani tushunishingiz mumkin, siz yaxshi misollarni ko'rishingiz mumkin va ular sizni g'ayrat bilan sinab ko'rishga imkon beradi. Bu hamma joyda, ayniqsa etishmayotgan joyda bo'lishi kerak. Ushbu videolar uchun va shunga o'xshash videolar uchun katta rahmat. Ular chinakam yordamdir va siz hamma narsani yaxshiroq bilib olasiz. Shuningdek, bizni narsalar bilan bog'laydigan va butun dunyo bo'ylab odamlarni bog'laydigan YouTube-ga rahmat !! :)",
  copyright: "© Copyright 2021 Barcha huquqlar himoyalangan",
  name: "Ism",
  age: "Yosh",
  eMail: "E-mail",
  address: "Manzil",
  subject: "Kasbi",
  omon: "Omon",
  address44: "Toshkent, Sergeli 44",
  developer: "Junior Developer",
  date: "2020, 10 Sentyabrdan",
  viewSite: "Ko'rish",
  contactMe: "Men bilan",
  me: "Bog'laning",
  contactMeText: "Iltimos, men bilan bog'lanish uchun quyidagi shaklni to'ldiring",
  contactName: "Ismingizni kiriting",
  contactEmail: "E-mailingizni kiriting",
  contactMessage: "Xabar kiriting",
  contactSubmit: "Topshirish",
}

const text = {
  en,
  ru,
  uz
}

export default text